from . import rscs_base_path

DEF_SEQ_LEN = 10
DEF_BUFFER_SIZE = 1000
DEF_BATCH_SIZE = 32
DEF_EMBEDDING_DIMENSION = 256
DEF_RNN_UNITS = 1024
DEF_EPOCH_COUNT = 50

MODELS_PATH = rscs_base_path.joinpath("models")

VOCAB_SIZE = 300
VOCAB_PLACEHOLDER = "UNDEF"
